import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Header } from "@/components/header/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header text="Language Day-by-Day"/>
        {children}
      </body>
    </html>
  );
}
