name: Test and Build on PR/MR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - uses: ./test.yaml@latest
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@latest
      - name: Use Node.js latest
        uses: actions/setup-node@latest
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build