name: CI Workflow

on: 
  push:
    branch: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint check
        run: npm run lint --fix-dry-run .
  test-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install jest dependencies
        run: npm ci
      - name: Run Next.js tests
        run: npm run test
  test-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start Storybook 
        run: npm run storybook -- --ci --port 6006 &
      - name: Wait for Storybook
        run: npx wait-on http://localhost:6006
      - name: Run Storybook tests
        run: npm run test:storybook
# TODO: consider cleaning up images to reduce space consumption, keep baseline, only keep current and diff if the test fails
  test-visual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start Storybook 
        run: npm run storybook -- --ci --port 6006 &
      - name: Wait for Storybook
        run: npx wait-on http://localhost:6006
      - name: Run Playwright test
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        with:
          path: __test__/visual/**/screenshots/
          name: images
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add __test__/visual/**/screenshots/
          git commit -m "Add Playwright test artifacts"
          git push
  build:
    runs-on: ubuntu-latest
    needs: [lint, test-jest, test-storybook, test-visual]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
