name: CI Workflow

on: 
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-version: 20
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node.outputs.node-version }}
      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lint check
        run: npm run lint --fix-dry-run .

  test-jest:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Next.js tests
        run: npm run test

  test-storybook:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Start Storybook
        run: npm run storybook -- --ci --port 6006 &
      - name: Wait for Storybook
        run: npx wait-on http://localhost:6006
      - name: Run Storybook tests
        run: npm run test:storybook
      - name: Stop Storybook
        run: kill $(lsof -t -i:6006)

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test-jest, test-storybook]
    steps:
      - name: Build project
        run: npm run build