name: Run Tests

on: 
  push:
    branch: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Use Node.js latest
        uses: actions/setup-node@latest
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Install test dependencies
        run: npm install --save-dev jest
      - name: Run Next.js tests
        run: npm test