# name: Test and Build on PR/MR

# on:
#   pull_request:
#   push:
#     branch: [ "**" ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: ./test.yaml@v1
#   build:
#     runs-on: ubuntu-latest
#     needs: test
#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js 20
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - name: Install dependencies
#         run: npm ci
#       - name: Build project
#         run: npm run build